Sc 3786/databricks move file on dbfs
shipyardapp/databricks-blueprints pull request #6
Opened 2022-07-05 13:36 UTC by Shamwayne

2022-07-21 19:31 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +    parser.add_argument('--source-folder-name', dest='source_folder_name', required=True)
Not required. Should use `/FileStore/` if blank

2022-07-21 19:38 UTC, blakeburch reviewed
1) Can't move a file into a directory that doesn't exist. Needs to handle that on Databricks side.
2) Needs to handle all different error scenarios.
3) Needs to be able to support moving multiple files through regex.

2022-07-21 19:38 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +    parser.add_argument('--dest-folder-name', dest='dest_folder_name', required=True)
Not required. Should use `/FileStore/` if blank

2022-07-21 19:38 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +    destination_file_path = shipyard.combine_folder_and_file_name(
`shipyard.files.`

2022-07-21 19:38 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +    source_file_path = shipyard.combine_folder_and_file_name(
`shipyard.files.`

2022-07-21 19:38 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +              "response: {move_response.text}")
Should be an f-string. Just prints out the text as is.

2022-07-21 19:38 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +    dest_folder_name = args.dest_folder_name
both folder name fields need to go through shipyard_utils cleaning

2022-07-27 21:06 UTC, blakeburch requested changes
1) I cannot get the files to actually move when using regex. It keeps telling me `DBFS /FileStore/10mb_file_test.csv to /FileStore/10mb_file_test.csv failed.`

In the above instance, I provided a dest-file-name, so the name should have been enumerated due to regex matching logic.

Functionality works fine on exact match.
2) Needs to handle errors better (file doesn't exist, no files matched to, bad instance-id, etc.)

2022-07-27 21:06 UTC, blakeburch commented on databricks_blueprints/helpers.py
> +    files_data = response.json()['files']
It looks like I'm able to break this if I provide a folder path that doesn't exist. 


```
files_data = response.json()['files']
KeyError: 'files'

```
We should error handle for that appropriately. [](edited-with-Axolo)

2022-07-27 21:06 UTC, blakeburch commented on databricks_blueprints/move_file_on_dbfs.py
> +              "response: {move_response.text} status: {move_response.status_code}")
Needs to be an f-string

2022-08-01 15:40 UTC, blakeburch commented
@Shamwayne As far as I can tell, the `list_dbfs_files` function is only listing files in the currently provided directory, not all subdirectories. Is this possible to achieve?

You can read from our Regex Documentation that the intended behavior is that searching for a file with regex means that the provided folder name is used as a "filter".

So providing "/FileStore/" should still look for regex matches against "/FileStore/test/folder/", "/FileStore/test/", "/FileStore/more/nested", "/FileStore/more" etc.

2022-08-01 16:19 UTC, Shamwayne commented
Assumed that was specifically for delete functionality and not across the board

2022-08-04 17:10 UTC, blakeburch approved these changes
Minor changes made. Good to go.

2022-08-04 17:10 UTC, merged